Add aditional arithmetic computations and validations
Kolesa-Education/kolesa-upgrade-homework-1 pull request #31
Opened 2022-09-16 05:51 UTC by znamazbayeva

2022-09-16 05:53 UTC, znamazbayeva commented
Added aditional arithmetic computations such as:
- comparison
- degree 
- percentage

and validations of inputs such as checking if :
- input is null
- input is numeric

2022-09-18 06:54 UTC, AKaliyev requested changes

2022-09-18 06:54 UTC, AKaliyev commented on index.php
> +  if(!(isset($_GET['a']) && isset($_GET['b']) && isset($_GET['c']))) {
можно все пихнуть в один isset

2022-09-18 06:54 UTC, AKaliyev commented on index.php
> +    exit("Please, check your inputes \n");
лучше чтобы метод просто возвращал результат проверки. а что делать дальше пусть решает, тот кто вызвал этот метод

2022-09-18 06:54 UTC, AKaliyev commented on index.php
> +  $arg_list = func_get_args();
думаю лучше просто использовать аргументы функции, и не использовать этот метод, так как это не совсем очевидно, ну а ты точно знаешь что будут 2 аргумента

2022-09-18 06:54 UTC, AKaliyev commented on index.php
> +      exit(($argIdx+1)."th argument is null. Please, enter an integer or float \n");
тут тоже просто лучше возвращать результат проверки, а что с этим делать дальше пусть решает вызывающий код

2022-09-18 06:54 UTC, AKaliyev commented on index.php
> +    if(empty($currentArgument)) {
тут получается, мы совсем не сможем 0 ввести. нужно исправить

2022-09-18 12:26 UTC, AKaliyev requested changes

2022-09-18 12:26 UTC, AKaliyev commented on index.php
> +  if(!(isset($_GET['a'], $_GET['b'], $_GET['c']))) {
можно сразу сделать типа `return isset($_GET['a'], $_GET['b'], $_GET['c']);`

2022-09-18 12:26 UTC, AKaliyev commented on index.php
> +  if(!is_numeric($firstInput) || !is_numeric($secondInput)) {
тут тоже можно сделать чтобы сразу возвращал результат проверки

2022-09-18 12:26 UTC, AKaliyev commented on index.php
> +        if ($b == 0) {
лучше юзать строгое сравнение `$b === 0`

2022-09-19 06:08 UTC, AKaliyev approved these changes

2022-09-19 06:08 UTC, closed without merging