выполняю задание 1
Kolesa-Education/kolesa-upgrade-homework-1 pull request #9
Opened 2022-09-14 11:19 UTC by UlanZhassanov

2022-09-16 11:50 UTC, apushevye approved these changes
Молодец  хорошая работа. Добавил несколько коментариев. Так держать!

2022-09-16 11:50 UTC, apushevye commented on index.php
> +
Пустые строки лишние, лучше их убрать

2022-09-16 11:50 UTC, apushevye commented on index.php
> +
тут тоже

2022-09-16 11:50 UTC, apushevye commented on index.php
> +
и тут

2022-09-16 11:50 UTC, apushevye commented on index.php
> +if (isset($_GET['a']) && isset($_GET['b'])  && isset($_GET['c'])) {
можно сделать обратную проверку и избавиться от вложенности

2022-09-16 17:30 UTC, apushevye requested changes
Меняю на Request Changes по просьбе студента

2022-09-17 06:19 UTC, apushevye requested changes
Нужно поправить моменты с выводом строки. Добавить конкатенация строк или использовать sprintf например.

2022-09-17 06:19 UTC, apushevye commented on index.php
> +                echo "$a > $b";
тут лучше использовать конкатенацию или через sprintf

2022-09-17 11:27 UTC, UlanZhassanov commented on index.php
> +                echo "$a > $b";
в compare добавил конкатенацию и для сообщения "не является оператором" применил sprintf

2022-09-19 04:55 UTC, apushevye commented
Молодец!

2022-09-19 04:55 UTC, closed without merging